sudo: required
services:
  - docker
env:
  global:
    # get latest commit SHA to apply as tag
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # decrypt encrypted service account
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d

  # download gsdk  & source config
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  # install kubectl within environment
  - gcloud components update kubectl

  # authenticate gsdk using service account
  - gcloud auth activate-service-account --key-file service-account.json

  # configure gsdk to use project/cluster
  - gcloud config set project multi-k8s-264611
  - gcloud config set compute/zone europe-west1-c
  - gcloud container clusters get-credentials multi-cluster

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Build & tag docker container
  - docker build -t travistkirton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run travistkirton/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
