sudo: required
services:
  - docker
before_install:
  # download gsdk  & source config
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  # install kubectl within environment
  - gcloud components update kubectl

  # authenticate gsdk using service account
  - gcloud auth activate-service-account --keyfile service-account.json

  # retrieve encrypted service account
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
